default:
    outputs:
        dev:
            type: snowflake
            threads: 4
            account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
            user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
            password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
            role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
            warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
            database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
            schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"