SELECT year,
       month,
       dayofmonth AS day_of_month,
       dayofweek AS day_of_week,
       deptime AS actual_dep_time,
       crsdeptime AS crs_dep_time,
       arrtime AS actual_arr_time,
       crsarrtime AS crs_arr_time,
       uniquecarrier AS unique_carrier,
       flightnum AS flight_num,
       tailnum AS tail_num,
       actualelapsedtime AS actual_elapsed_time,
       crselapsedtime AS crs_elapsed_time,
       airtime AS air_time,
       arrdelay AS arr_delay,
       depdelay AS dep_delay,
       origin,
       dest,
       distance,
       taxiin AS taxi_in,
       taxiout AS taxi_out,
       cancelled,
       cancellationcode AS cancellation_code,
       diverted,
       DECODE(carrierdelay, 'NA', NULL, carrierdelay) AS carrier_delay,
       DECODE(weatherdelay, 'NA', NULL, weatherdelay) AS weather_delay,
       DECODE(nasdelay, 'NA', NULL, nasdelay) AS nas_delay,
       DECODE(securitydelay, 'NA', NULL, securitydelay) AS security_delay,
       DECODE(lateaircraftdelay, 'NA', NULL, lateaircraftdelay) AS late_aircraft_delay
  FROM {{ source('src_flight', 'flights') }}